### ISSUE TITLE
ReferenceError: times is not defined

### ISSUE THREAD

**Issue by thehappydinoa** [jonluca/RideShare-Trip-Stats#1]
```
Error in event handler for (unknown): ReferenceError: times is not defined
    at addNumTripsChart (chrome-extension://kddlnbejbpknoedebeojobofnbdfhpnm/js/main.js:333:21)
    at startStatistics (chrome-extension://kddlnbejbpknoedebeojobofnbdfhpnm/js/main.js:314:3)
    at chrome-extension://kddlnbejbpknoedebeojobofnbdfhpnm/js/main.js:9:5
```

**Comment by jonluca** [comment]
Fixed in 28778112f84ead5838077e430c0117afd5651c47, thanks!
